### ISSUE TITLE
compability with meteor 0.9.0

### ISSUE THREAD

**Issue by seliverstov** [oortcloud/heroku-buildpack-meteorite#52]
After migration to meteor/meteorite 0.9.0 my app was successfuly deployed to heroku, but after that it crashes during startup with error. On my local machine it works fine with new meteor release. Problem occurs only on Heroku.

2014-08-28T07:47:18.713911+00:00 app[web.1]:
2014-08-28T07:47:18.714803+00:00 app[web.1]:     throw err;
2014-08-28T07:47:18.714972+00:00 app[web.1]:           ^
2014-08-28T07:47:18.721180+00:00 app[web.1]: Error: Cannot find module 'fibers'
2014-08-28T07:47:18.721184+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2014-08-28T07:47:18.721186+00:00 app[web.1]:     at Function.Module._load (module.js:280:25)
2014-08-28T07:47:18.721187+00:00 app[web.1]:     at Module.require (module.js:364:17)
2014-08-28T07:47:18.721190+00:00 app[web.1]:     at require (module.js:380:17)
2014-08-28T07:47:18.721191+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:1:75)
2014-08-28T07:47:18.721193+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2014-08-28T07:47:18.721194+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2014-08-28T07:47:18.721196+00:00 app[web.1]:     at Module.load (module.js:356:32)
2014-08-28T07:47:18.721198+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2014-08-28T07:47:18.721199+00:00 app[web.1]:     at Module.require (module.js:364:17)
2014-08-28T07:47:18.714488+00:00 app[web.1]: module.js:340
2014-08-28T07:47:19.702080+00:00 heroku[web.1]: Process exited with status 8
2014-08-28T07:47:17.535884+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2014-08-28T07:47:19.713767+00:00 heroku[web.1]: State changed from crashed to starting
2014-08-28T07:47:19.713185+00:00 heroku[web.1]: State changed from starting to crashed
2014-08-28T07:47:23.344818+00:00 app[web.1]:     throw err;
2014-08-28T07:47:23.343796+00:00 app[web.1]:
2014-08-28T07:47:23.347405+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2014-08-28T07:47:23.347408+00:00 app[web.1]:     at Module.require (module.js:364:17)
2014-08-28T07:47:23.347414+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2014-08-28T07:47:23.347399+00:00 app[web.1]: Error: Cannot find module 'fibers'
2014-08-28T07:47:23.347407+00:00 app[web.1]:     at Function.Module._load (module.js:280:25)
2014-08-28T07:47:23.347415+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2014-08-28T07:47:23.344824+00:00 app[web.1]:           ^
2014-08-28T07:47:23.347412+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:1:75)
2014-08-28T07:47:23.347410+00:00 app[web.1]:     at require (module.js:380:17)
2014-08-28T07:47:23.347417+00:00 app[web.1]:     at Module.load (module.js:356:32)
2014-08-28T07:47:23.347418+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2014-08-28T07:47:23.347420+00:00 app[web.1]:     at Module.require (module.js:364:17)
2014-08-28T07:47:23.344388+00:00 app[web.1]: module.js:340
2014-08-28T07:47:24.152741+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by jononomo** [comment]
I've switched over to Arunoda's `mupx` tool.  Can this issue be closed?

**Comment by lirbank** [comment]
@jononomo I guess there is no activity in this repo anymore as Meteorite is deprecated as of Meteor 1.0, see the [README](https://github.com/oortcloud/heroku-buildpack-meteorite/blob/master/README.md)

> Meteorite is no longer used as of Meteor > 1.0. There are other buildpacks that support Meteor 1.0.

A good alternative is https://github.com/AdmitHub/meteor-buildpack-horse
